### ISSUE TITLE
namcap errors about missing libraries

### ISSUE THREAD

**Issue by kiendang** [julie-is-late/aur-libnvidia-container#2]
Errors when running [namcap](https://wiki.archlinux.org/index.php/Creating_packages#Checking_package_sanity) on the built packages

```sh
namcap libnvidia-container-1.0.0-1-x86_64.pkg.tar

libnvidia-container E: Dependency libelf detected and not included (libraries ['usr/lib/libelf.so.1'] needed in files ['usr/lib/libnvidia-container.so.1.0.0'])
```

```sh
namcap libnvidia-container-tools-1.0.0-1-x86_64.pkg.tar

libnvidia-container-tools E: Dependency libtirpc detected and not included (libraries ['usr/lib/libtirpc.so.3'] needed in files ['usr/bin/nvidia-container-cli'])
```

Probably because specific versions of `libelf` and `libtirpc` were used but not included in the packages?
I don't have this problem with `libnvidia-container-bin` and `libnvidia-container-tools-bin` which use the rpm packages. Let me check how they did it.

**Comment by kiendang** [comment]
Ok I think it was built without `libelf` and `libtirpc`.

This is on centos after installing `libnvidia-container1` and `libnvidia-container-tools`:
```sh
[root@b2ede36c5c2e /]# ldd /usr/lib64/libnvidia-container.so.1.0.1
	linux-vdso.so.1 =>  (0x00007fff9b3b4000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f0c0ec4d000)
	libcap.so.2 => /lib64/libcap.so.2 (0x00007f0c0ea48000)
	libseccomp.so.2 => /lib64/libseccomp.so.2 (0x00007f0c0e807000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f0c0e43a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0c0f477000)
	libattr.so.1 => /lib64/libattr.so.1 (0x00007f0c0e235000)
```

```sh
[root@b2ede36c5c2e /]# ldd /usr/bin/nvidia-container-cli
	linux-vdso.so.1 =>  (0x00007ffc5b7d6000)
	libnvidia-container.so.1 => /usr/bin/../lib64/libnvidia-container.so.1 (0x00007feb31cc0000)
	libcap.so.2 => /usr/bin/../lib64/libcap.so.2 (0x00007feb31abb000)
	libc.so.6 => /usr/bin/../lib64/libc.so.6 (0x00007feb316ee000)
	libdl.so.2 => /usr/bin/../lib64/libdl.so.2 (0x00007feb314ea000)
	libseccomp.so.2 => /usr/bin/../lib64/libseccomp.so.2 (0x00007feb312a9000)
	libattr.so.1 => /usr/bin/../lib64/libattr.so.1 (0x00007feb310a4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007feb324ef000)
```

**Comment by julie-is-late** [comment]
fixed these errors in https://github.com/jshap70/aur-libnvidia-container/commit/d056cd0beecf300242c8a2217939d65d11795157, however it still has some warnings: 
```
> namcap libnvidia-container-*
libnvidia-container-tools W: Unused shared library '/tmp/../lib/libtirpc.so.3' by file ('usr/bin/nvidia-container-cli')
libnvidia-container-tools W: Dependency libcap included but already satisfied
libnvidia-container-tools W: Dependency libtirpc included but already satisfied
```

**Comment by kiendang** [comment]
yea this is tricky. im messing around with PKGBUILD now see what i can do.

**Comment by julie-is-late** [comment]
my guess is those libs are built statically into the cli elf and the warning is saying they're also available dynamically from deps. maybe there's a way to stip those symbols specifically? I'm afraid to mess around with it too much though.

**Comment by kiendang** [comment]
I think can ignore the first warning. The others were addressed in https://github.com/jshap70/aur-libnvidia-container/pull/5/commits/832685e6f80f6cbb1b9e0bb1075eb466c84b868b.

**Comment by julie-is-late** [comment]
closing as resolved

**Comment by kiendang** [comment]
Managed to fix `libnvidia-container-tools W: Unused shared library '/tmp/../lib/libtirpc.so.3' by file ('usr/bin/nvidia-container-cli')`. Will make a PR soon.

**Comment by julie-is-late** [comment]
what ended up being the issue?

edit: ignore me accidentally closing the issue :confounded:
