### ISSUE TITLE
ver 1.0.1

### ISSUE THREAD

**Issue by kiendang** [julie-is-late/aur-libnvidia-container#3]
The prebuilt `.rpm`, `.deb`... packages are already version 1.0.1. I think they just don't release on github anymore.

I suggest change source to `git+https://github.com/NVIDIA/libnvidia-container.git#commit=fe20a8e4a17a63df8116f39795173a461325fb3d` and shas56sums to `SKIP` like I did with [nvidia-container-runtime](https://github.com/kiendang/aur-nvidia-container-runtime/blob/4602bf6e7b1ebe2184fde8f45bacf5777683236c/PKGBUILD#L13-L16).

**Comment by julie-is-late** [comment]
afaik using git commits is discouraged for src packages.  
I pinged the guy who pushed that commit and asked if there should have been a new release, so we'll see what he says.

**Comment by julie-is-late** [comment]
new release was made :)
